nonsoolmate-official/nonsoolmate-server

- .github/release-drafter-config.yml
- .github/workflows/dev-CD.yml
- .github/workflows/prod-CD.yml
- .github/workflows/prod-CI.yml
- .github/workflows/release-drafter.yml
- setting/#1 -> dev
- closed #1
- dev 브랜치 기준으로 이전 앱잼 레포지터리에 있던 커밋 기록을 미러 푸시로 가져왔습니다
- DEV, PROD 환경의 CI, CD를 분리했습니다
- Github Release Drafter로 자동화를 했습니다
> [SETTING] 프로젝트 이사

- .github/workflows/dev-CD.yml
feat/#14 -> dev
closed #14
- cd가 실패해서 수정했는데 수정 후에 또 오류 발생할 수도 있습니다..!
> [FIX] cd 스크립트 수정

- .github/workflows/dev-CD.yml
- fix/#19
- closed #19
- scp 실행 위치를 ssh 접속 이전으로 수정했습니다
- feat/#19로 이전에 만드셔서 그냥 같은 이슈 공유하도록 fix/#19로 했습니더!
> [FIX] dev-CD scp 명령어 실행 job 변경

- .github/workflows/dev-CD.yml
- fix/#27 -> dev
- closed #27
- scp 접속 시 dev_server_ip를 사용하도록 수정했습니다
> [FIX] scp 접속 시 hostname이 아닌 dev_server_ip로 접속하도록 수정

- nonsoolmateServer/src/main/resources/application-prod.yml
- setting/#29 -> dev
- application-secret.properties 수정
- application-prod.yml 수정
- 변경 properties 노션에 남겨두었습니다!
> [SETTING] application-prod.yml aws 관련 변수 분리

- nonsoolmateServer/src/main/resources/application-dev.yml
- nonsoolmateServer/src/main/resources/application-prod.yml
> [CHORE] 레디스 url 변경

- nonsoolmateServer/src/main/resources/application-dev.yml
infra/#47 -> dev
clsoed #47 
- 로컬호스트에서 컨테이너를 가리키도록 수정했습니다.
> [INFRA] localhost -> redis로 수정

- nonsoolmateServer/src/main/resources/application-dev.yml
- nonsoolmateServer/src/main/resources/application-local.yml
- nonsoolmateServer/src/main/resources/application-prod.yml
fix/#49 -> dev
closed #49
- 제가 옛날에 yml 작업하다가 osiv 설정을 빼먹은거 같네여.. 추가했습니다!
- 그리고 yml local,dev,prod 통일성있게 살짝 순서 변경했습니다!
> [FIX] osiv 끄기 및 yml 정리

- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/config/SecurityConfig.java
- nonsoolmateServer/src/main/resources/application-dev.yml
- nonsoolmateServer/src/main/resources/application-local.yml
- nonsoolmateServer/src/main/resources/application-prod.yml
- nonsoolmateServer/src/main/resources/application-test.yml
- feat/#51 -> dev
- closed #51
- yml에 서버/클라 origin 추가했습니다
- 수정된 application-secret 노션에 업데이트 했습니다
- corsConfigurer에 추가된 origin 반영했습니다
- 저희가 허용하는게 도메인이 아니라 origin을 허용한다고 생각하여 변수명을 수정했습니다!
> [FEAT] corsConfigurer에 테스트 서버/클라 Origin 추가

- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/controller/ExamRecordController.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/entity/ExamRecord.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/repository/ExamRecordRepository.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/service/ExamRecordService.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/controller/ServerInitController.java
chore/#58 -> dev
closed #58 
- 데모데이를 위해 코드 수정이 있는데 이게 서비스 로직은 그대로 두고, 하고 싶었지만 당장 좋은 방법이 떠오르지 않아 이렇게 구현했습니다..!
> [CHORE] 데모데이를 위한 기능 수정

- nonsoolmateServer/src/main/resources/application-local.yml
- [] 기능 수정
chore/#54 -> dev
closed #54 
- local yml에서 해당 설정을 하면, schema.sql 이 필요없어서 해당 설정 넣었습니다!
- 어차피 로컬이라 ddl-auto는 create로 둬도 무방하다고 생각했습니다!
- 이로써, 더이상 schema.sql 를 개발자가 따로 관리하지 않아도 되도록 했습니다!
- 다만, data.sql의 위치를 init 파일내부에서 resources 디렉토리 바로 아래로 수정해야합니다!
> [CHORE] local yml 수정

- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/controller/ServerInitController.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/controller/ServerInitService.java
> [FIX] 초기화 메서드 수정

- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/payment/controller/PaymentController.java
- nonsoolmateServer/src/main/resources/application-dev.yml
- nonsoolmateServer/src/main/resources/application-local.yml
- nonsoolmateServer/src/main/resources/application-prod.yml
- nonsoolmateServer/src/main/resources/application-test.yml
- feat/#66 -> dev
- closed #66
- 결제 연동 테스트를 위해 비즈니스 로직을 제외하고 임시적으로 컨트롤러 개발했습니다
> [FEAT] 결제 확인을 위한 임시 컨트롤러 개발

- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/service/AuthService.java
- fix/#70 -> dev
- closed #70
- 네이버 소셜 로그인 saveAndFlush -> save로 변경했습니다
- 앱잼 때 급하게 구현해서 놓친 부분이 많은 것 같습니다ㅎ..
> [FIX] 네이버 소셜 로그인 saveAndFlush -> save로 변경

- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/error/GlobalExceptionHandler.java
- feat/#74 -> dev
- closed #74
- 에러 메시지와 에러트레이스를 함께 출력하여 가독성 좋게 변경했습니다
> [FEAT] 에러 메시지와 에러트레이스를 함께 출력하여 가독성 좋게 변경

- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/entity/ExamRecord.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/entity/enums/EditingType.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/service/ExamRecordService.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/payment/entity/Billing.java
- feat/#80 -> dev
- closed #80 
- ExamRecord에 Enum 타입으로 첨삭과 재첨삭을 구분할 수 있는 필드를 추가했습니다
- Billing 엔티티에 OneToOne으로 외래키를 추가했습니다
> [FEAT] examRecord에 재첨삭 플로우에 따른 enum 추가

- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/entity/enums/ExamResultStatus.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectCollege/controller/dto/response/SelectCollegeExamResponseDTO.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectCollege/service/SelectCollegeService.java
- feat/#95 -> dev
- closed #95
- ExamResultStatus에 EXAM_BEFORE를 추가했습니다
- SelectCollegeExamResponseDTO에 설명을 추가했습니다
> [REFACTOR] BEFORE_EXAM을 enum에 포함시키기

- .github/workflows/prod-CD.yml
- infra/#98 -> dev 
- closed #98
- prod-CD에서 분리한 dockerhub repository(nonsoolmate-prod-server) 이름으로 변경했습니다.
> [INFRA] Docker repository 분리에 따른 prod-CD 스크립트 변경

- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/entity/ExamRecordGroups.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/repository/ExamRecordRepository.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectCollege/controller/dto/response/SelectCollegeExamResponseDTO.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectCollege/controller/dto/response/SelectCollegeExamsResponseDTO.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectCollege/repository/SelectCollegeRepository.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectCollege/service/SelectCollegeService.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/entity/College.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/entity/Exam.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/entity/University.java
- nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/repository/ExamRepository.java
- nonsoolmateServer/src/test/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/entity/ExamRecordGroupsTest.java
refactor/#100 -> dev
closed #100
```
Hibernate: 
select
sc1_0.select_college_id,
sc1_0.college_id,
sc1_0.member_id 
from
select_college sc1_0 
join
college c1_0 
on c1_0.college_id=sc1_0.college_id 
join
university u1_0 
on u1_0.university_id=c1_0.university_id 
where
sc1_0.member_id=? 
order by
u1_0.university_name,
c1_0.college_name
Hibernate: 
select
e1_0.exam_id,
e1_0.college_id,
e1_0.exam_answer_file_name,
e1_0.exam_file_name,
e1_0.exam_name,
e1_0.exam_time_limit,
e1_0.exam_year 
from
exam e1_0 
where
e1_0.college_id=? 
order by
e1_0.exam_year desc
Hibernate: 
select
er1_0.exam_record_id,
er1_0.editing_type,
er1_0.exam_id,
er1_0.exam_record_result_file_name,
er1_0.exam_record_sheet_file_name,
er1_0.exam_result_status,
er1_0.member_id,
er1_0.time_take_exam 
from
exam_record er1_0 …
```
> [REFACTOR] 단과 대학별 시험 리스트 조회 로직 개선

- .github/workflows/dev-CD.yml
- .github/workflows/dev-CI.yml
- .github/workflows/prod-CD.yml
- .github/workflows/prod-CI.yml
> [FIX] cd 스크립트 변경

- .github/workflows/dev-CD.yml
- .github/workflows/dev-CI.yml
- .github/workflows/prod-CD.yml
- .github/workflows/prod-CI.yml
> [FIX] ci,cd 스크립트 변경

- .github/workflows/dev-CD.yml
- .github/workflows/dev-CI.yml
- .github/workflows/prod-CD.yml
> [FIX] 배포스크립트 수정

- nonsoolmate-api/Dockerfile
> [FIX] 도커파일 수정

- nonsoolmate-db-core/src/main/java/com/nonsoolmate/payment/entity/Billing.java
- feat/#123 -> dev
- closed #123
- 사용자가 카드 변경을 진행할 때 복수의 카드를 추가하는 개념이 아니라 회원 당 하나의 카드를 등록한다고 기획측에서 말씀해주셔서 pk가 변경되는 플로우가 어색하여 billingId 컬럼을 추가했습니다
> [FEAT] billing 엔티티 billingId 컬럼 추가 및 pk 변경

- nonsoolmate-api/src/main/java/com/nonsoolmate/selectCollege/service/SelectCollegeService.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/selectCollege/repository/SelectCollegeRepository.java
closed #135 
- 선택 대학 조회 로직을 수정했습니다.
- 로직을 보니까 Repo 쪽에 반환타입으로 Set 자료형이 있더라고요?! 이걸 누가했는지 정확히 기억은 안나지만 만약 성은님 수정하신 기억이 있고, 의도가 있으셨다면 한 번 말씀주시면 감사하겠습니다!
> [FIX] 선택 대학 조회 로직 수정

- nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MemberApi.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MyController.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/request/ProfileRequestDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/service/MemberService.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/entity/Member.java
feat/#133 -> dev
closed #133
- 내 프로필 수정 API를 구현했습니다.
> [FEAT] 내 프로필 수정 API 구현

- nonsoolmate-api/src/test/java/com/nonsoolmate/payment/service/BillingServiceTest.java
- test/#141 -> dev
- closed #141
- #140 에서 작성하지 못했던 테스트 코드를 작성했습니다!
> [TEST] 카드 등록 API 서비스 계층 테스트코드 작성

- nonsoolmate-api/src/main/java/com/nonsoolmate/selectCollege/controller/SelectCollegeController.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/selectCollege/controller/dto/request/SelectUniversityRequestDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/selectCollege/controller/dto/response/SelectCollegeExamsResponseDTO.java
- fix/#145 -> dev
- closed #145
- 응답값 통일이 안된 부분, 그리고 카멜케이스로 작성되지 않은 부분을 수정했습니다
> [FIX] College 관련 필드 응답값 수정

- nonsoolmate-db-core/src/main/java/com/nonsoolmate/discount/entity/Discount.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/discount/entity/enums/DiscountType.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/discountProduct/entity/DiscountProduct.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/product/entity/Product.java
- feat/#154 -> dev
- closed #154
- 설계 참고 테크 스펙: https://www.notion.so/nonsoolmatee/Product-Discount-DiscountProduct-20af03279d9947e3842b323b0ba5ceff?pvs=4
- 설계한 ERD
- 리뷰받고 최종적인 스키마가 확정되면 merge 전에 스키마를 업데이트하겠습니다!
> [FEAT] Discount, DiscountProduct 엔티티 설계 및 구현

- nonsoolmate-api/src/main/java/com/nonsoolmate/global/dto/TagDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MemberApi.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MyController.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/TeacherResponseDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/service/MemberService.java
- nonsoolmate-api/src/test/java/com/nonsoolmate/domain/examRecord/entity/ExamRecordGroupsTest.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/matching/repository/MatchingRepository.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/tag/entity/Tag.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/tag/repository/TagRepository.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/teacher/repository/TeacherRepository.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/teacher/repository/TeacherUniversityRepository.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/university/entity/University.java
- feat/#137 -> dev
- closed #137 
- `내 첨삭 선생님 조회 API` 를 개발했습니다.
- `Tag` 와 `University` 엔티티에 이미지가 필요할 거 같아 컬럼을 추가했습니다. 이에 대한 의견 궁금합니다!
- 첨삭 선생님 매칭이 되지 않은 경우 `204` 를 반환하도록 했습니다.
> [FEAT] 내 첨삭 선생님 조회 API 개발

- nonsoolmate-api/src/main/java/com/nonsoolmate/coupon/service/CouponService.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/couponMember/repository/CouponMemberRepository.java
- fix/#158 -> dev
- closed #158 
- 쿠폰 등록 로직을 수정했습니다. 
- 이미 등록된 쿠폰 처리가 미흡하여 보완했습니다.
- 쿠폰과 회원의 관계가 N:N인데 예전에 1:1 로 생각하고 진행한거 같습니다!
> [FIX] 쿠폰 등록 로직 수정

- nonsoolmate-api/src/main/java/com/nonsoolmate/targetUniversity/controller/TargetUniversityApi.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/targetUniversity/controller/TargetUniversityController.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/targetUniversity/controller/dto/TargetUniversityResponseDto.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/targetUniversity/service/TargetUniversityService.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/targetUniversity/repository/TargetUniversityRepository.java
- feat/#163 -> dev
- closed #163 
- 목표대학 조회 기능을 구현했습니다.
> [FEAT] 목표대학 조회 API 

- nonsoolmate-batch/build.gradle
- nonsoolmate-batch/src/main/java/com/nonsoolmate/NonsoolmateBatchApplication.java
- nonsoolmate-batch/src/main/java/com/nonsoolmate/config/QuerydslConfig.java
- nonsoolmate-batch/src/main/java/com/nonsoolmate/payment/BillingPaymentService.java
- nonsoolmate-batch/src/main/java/com/nonsoolmate/payment/BillingScheduler.java
- nonsoolmate-batch/src/main/resources/application.yml
- nonsoolmate-common/src/main/java/com/nonsoolmate/exception/member/MembershipExceptionType.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/coupon/entity/Coupon.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/couponMember/entity/CouponMember.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/entity/Membership.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/repository/MembershipRepository.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/order/entity/OrderDetail.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/order/repository/OrderRepository.java
- feat/#167 -> dev
- closed #167 
- 빌링 자동 결제를 구현했습니다.
- 기존 결제로직과 동일하게 가는게 관리하기 편할 것 같아서 최대한 비슷하게 진행했습니다.
- 테스트를 어떻게 하는게 좋을지 여쭤보고 싶습니다!
> [FEAT] 빌링 자동 결제 구현

- nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MemberApi.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/TeacherResponseDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/service/MemberService.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/matching/entity/Matching.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/matching/repository/MatchingRepository.java
- chore/#183 -> dev
- closed #183
> [CHORE] 첨삭 선생님 조회 status 추가

- nonsoolmate-api/src/main/java/com/nonsoolmate/member/service/MembershipService.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/selectCollege/service/SelectCollegeService.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/targetUniversity/controller/TargetUniversityApi.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/targetUniversity/controller/TargetUniversityController.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/targetUniversity/controller/dto/request/TargetUniversityRequestDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/targetUniversity/controller/dto/response/TargetUniversityResponseDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/targetUniversity/service/TargetUniversityService.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/targetUniversity/entity/TargetUniversity.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/targetUniversity/repository/TargetUniversityRepository.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/university/repository/UniversityRepository.java
- feat/#171 -> dev
- closed #171 
- 목표대학 선택 API를 구현했습니다
> [FEAT] 목표 대학 선택 API 구현

- nonsoolmate-api/src/main/java/com/nonsoolmate/coupon/controller/CouponApi.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/coupon/controller/CouponController.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/coupon/controller/dto/request/ApplyCouponRequestDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/coupon/controller/dto/request/RegisterCouponRequestDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/coupon/service/CouponService.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/couponMember/entity/CouponMember.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/couponMember/repository/CouponMemberRepository.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/order/entity/OrderDetail.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/order/repository/OrderRepository.java
- nonsoolmate-exception/src/main/java/com/nonsoolmate/exception/order/OrderException.java
- nonsoolmate-exception/src/main/java/com/nonsoolmate/exception/order/OrderExceptionType.java
- feat/#165 -> dev
- closed #165 
- 쿠폰 사용 로직을 구현했습니다.
> [FEAT] 쿠폰 사용 API

- nonsoolmate-api/src/main/java/com/nonsoolmate/global/dto/TagDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/TeacherResponseDTO.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/teacher/entity/Teacher.java
- fix/#207 -> dev
- closed #207 
- 스웨거 응답 수정했습니다.
엔티티에 추가 및 Dto에도 boolean 값으로 인증 여부를 추가했습니다!
> [FIX] 스웨거 response 수정

- nonsoolmate-api/src/main/java/com/nonsoolmate/coupon/controller/dto/response/GetCouponResponseDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/coupon/service/CouponService.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/couponMember/repository/CouponMemberCustomRepositoryImpl.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/couponMember/repository/CouponMemberRepository.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/couponMember/repository/dto/CouponResponseDTO.java
- fix/#201 -> dev
- closed #201 
- 저번에 쿠폰 필드 수정이 있었는데 여기는 고려하지 못했었네요..! 그래서 수정했습니다!
- 쿠폰 조회에서는 사용될 or 사용한 쿠폰은 조회되지 않도록 수정했습니다!
> [FIX] 쿠폰 목록 조회 응답값 수정

- nonsoolmate-db-core/src/main/java/com/nonsoolmate/product/entity/Product.java
- fix/#217 -> dev
- closed #217 
- 세일 가격 계산 로직에서 실수가 있었습니다.
> [FIX] 쿠폰사용한 세일 가격 계산 로직 수정

- nonsoolmate-external/src/main/java/com/nonsoolmate/email/service/EmailService.java
- nonsoolmate-external/src/main/resources/templates/examRecordStatusTemplate.html
- chore/#215 -> dev
- closed #215 
- 이메일 템플릿에서 이모지 변경 및 실제 이메일에서 버튼 클릭이 안되는 문제를 해결했습니다
> [CHORE] 이메일 템플릿 변경

- nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/TeacherResponseDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/service/MemberService.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/teacher/entity/Teacher.java
- chore/#220 -> dev
- closed #220 
- 질의 응답 링크 추가했습니다.
> [CHORE] 질의 응답 링크 추가

- .github/workflows/dev-CD.yml
- .github/workflows/prod-CD.yml
- nonsoolmate-batch/src/main/java/com/nonsoolmate/scheduler/BillingScheduler.java
- nonsoolmate-batch/src/main/resources/application-dev.yml
- nonsoolmate-batch/src/main/resources/application-prod.yml
- nonsoolmate-batch/src/main/resources/application-test.yml
- nonsoolmate-batch/src/test/java/com/nonsoolmate/nonsoolmatebatch/NonsoolmateBatchApplicationTests.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/entity/Membership.java
- nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/repository/MembershipRepository.java
- chore/#187 -> dev
- closed #187 
- CI/CD 에 배치 서버도 배포되도록 수정했습니다.
- 배치 서버도 dev, prod 버전을 만들었는데 의견 궁금합니다!
- 빌링 결제 할 때, 'endDate'가 만료된 멤버십에 한해서 빌링 결제를 시도하도록 구현했습니다!
> [CHORE] 배치 시스템 수정

- nonsoolmate-batch/Dockerfile
> [FIX] 배치 내부에 dockerfile 추가

- nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/TeacherResponseDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/TeacherUniversityDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/member/service/MemberService.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/targetUniversity/controller/dto/response/TargetUniversityResponseDTO.java
- nonsoolmate-api/src/main/java/com/nonsoolmate/targetUniversity/service/TargetUniversityService.java
- nonsoolmate-external/src/main/java/com/nonsoolmate/aws/FolderName.java
- feat/#222 -> dev
- closed #222 
- 클라우드 프론트를 통해 이미지를 받아오도록 서비스 로직을 변경했습니다
- 이미지 화질 문제가 있어 기획에 문의드린 상태입니다!
- 충돌나서 DTO, service가 수정되었는데 누락된게 없는지 확인부탁드립니다!
> [FEAT] 대학교 이미지 경로를 불러오도록 서비스 로직 변경
