nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/aop/ExecutionLoggingAop.java

feat/#3 -> dev
closed #3
- 앞으로 실제 서비스 및 에러 디버깅을 위해 필요한 로깅 정보가 남도록 설정했습니다.
- 도커 컨테이너에서 EC2 호스트와 볼륨을 마운트해서 로깅 내용이 영구적으로 쌓이게 할 수 있는데 그 부분까진 구현하진 않았습니다!
* 로깅 내용은 아래와 같습니다.
* 요청된 컨트롤러 클래스 이름
* 요청된 유저 id
* 요청값
* 전체 실행시간
- 관련해서 수정 필요한 부분 있다면 편하게 말씀주세요 !!

[FEAT] 로깅 AOP 구현

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/controller/SelectUniversityController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/repository/SelectUniversityRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectUniversity/service/SelectUniversityService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/repository/UniversityRepository.java

feat/#6 -> dev
closed #6
- 허허,,, 테스트 코드를 작성하려다가 코드를 이것저것 살펴보면서 제가 1월에 작성한 코드를 다시 봤는데 말이 안되더라고요,,,
- 가독성이 최악이고, db쿼리도 말도 안되게 나가는 것 같아서 이 부분 간단히 개선해봤습니다!
- 기존에 대학 조회 쿼리도 N번 나가는 구조여서 이 부분 1번 쿼리로 개선했습니다!
- delete 쿼리도 bulk성으로 1번만 발생하지만, insert 쿼리는 요청한 수 만큼 나가는 구조인데요!
- 사실 저희 insert 쿼리가 끽해야 50번 미만일것 같아서 크게 문제 없다고 판단이 들어 이렇게 구현했습니다!
- 간단한 방법으로 jpa의 batch insert가 있을 것 같은데요! 적용하기엔 저희 엔티티 id 생성전략이 `IDENTITY` 로 되어 있어서 간단히 적용하긴 어려울 것 같아서 이렇게 PR 날려봅니다..!
- 참고자료 : https://cheese10yun.github.io/jpa-batch-insert/
- insert(`saveAll`)와 통일성있게 delete도 `deleteAll` 이 더 좋다고 생각 드시면 편하게 의견 말씀주세요!!

[REFACTOR] 목표대학 설정 API 리팩토링

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/UniversityApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/UniversityExamController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/dto/response/UniversityExamFileResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/entity/UniversityExam.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/exception/UniversityExamSuccessType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/service/UniversityExamService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/aws/FolderName.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/jwt/utils/PasswordUtil.java

- feat/#5 -> dev
- closed #5 
- UniversityExam 엔티티에 시험 문제 Pdf 경로를 저장할 필드를 추가했습니다(university_exam_file_name)
- db 스크립트(create, dummy) 노션에 업데이트 해두었습니다!
- Rds에는 alter문으로 컬럼 추가해두었습니다
- 현재 제 로컬에서는 시험지명이 영어일 때만 조회가 가능한 상황입니다(사진 첨부) 그러나 인코딩 문제라기에는 한글이름으로 되어있는 시험 문제 이미지는 조회가 잘 되는 상황입니다
- 민규님 로컬에서 한 번 실행해보고 문제 없으면 test 서버에까지 반영된 이후에 클라테스트 해보는게 좋을 것 같습니다! 관련해서는 좀 더 찾아보겠습니도  
- @mikekks 그리고 현재 password를 제가 주석처리해두었는데 저희 서비스에서 필요하지 않은 기능인 것 같아서 관련 클래스를 지우는건 어떨지 여쭤봅니다!!

[FEAT] 시험지 조회(PDF) 구현

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/UniversityApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/UniversityExamController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/dto/response/UniversityExamAndAnswerResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/dto/response/UniversityExamFileResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/exception/UniversityExamSuccessType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/service/UniversityExamService.java

- feat/#9 -> dev
- closed #9
- 문제 이미지와 해제 pdf를 반환하던 기능을 문제 pdf로 조회하도록 새롭게 기능을 만들었습니다
- 현재 기존 API가 클라분들 Q/A 하실 때 계속 사용중이시기도하고 아직 PDF로 수정작업을 안하고계셔서 앞에 /v2를 넣어 기존 경로와 다르게 설정해두었습니다
- 나중에는 v2 뺀 경로대로 배포하면 될 것 같습니도
- pdf URL 문제 저도 복붙해서 해결했습니다 ㅎ.ㅎ 감사합니다
- 저는 이게 제 기능인줄 알았는데 명세서보니까 오빠가 구현했던 기능이더라고요! 그래서 responseDTO 필드명을 확인하게 되었는데 오빠랑 저랑 통일감이 없어서 일요일 회의 때 논의하면 좋을 것 같습니다!

[FEAT] 해제: 문제PDF_해제PDF 조회 기능 구현

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/MemberApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/MyController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/controller/dto/response/ProfileResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/exception/MemberSuccessType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/repository/MemberRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/service/MemberService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/service/MemberAuthService.java

feat/#23 -> dev
closed #23 
- 사실 컨트롤러에서 받은 Member를 사용하여 굳이 service레이어 까지 내려갈 필요 없이 구현할 수 있는데요! 
- 그럼에도 불구하고, 이렇게 구현한 이유는 그러한 패턴이 안티패턴이라고 들어서 그랬습니다..!
- 사실 지금 서비스 레이어까지 내려가지 않더라도 크게 문제는 없습니다! 
- 문제가 생기는 시점은 Member 테이블에 `@oneToMany `나 `@ManyToOne `과 같이 연관관계가 붙기 시작할 때 부터인데요!
- 저희가 osiv가 false로 설정되어 있는 만큼 영속성 컨텍스트가 서비스 레이어부터 시작되는데요! 
- 하지만 컨트롤러에서 받은 `Member` 객체는 필터 단에서 조회한 것이잖아요??
- 그래서 Lazy loading 으로 연관관계가 있는 객체를 조회할 때, `LazyInitializationException` 이 발생합니다! 
- 추후에 이런 오류를 고려하여 이렇게 코드를 작성했습니다!
- 번외로 이러한 이슈 때문에 스프링 시큐리티에 Member 객체 전부를 넣는 것보다 memberId만 넣어서 service 레이어에서 멤버 객체를 조회하는게 더 나은 패턴이라고 하더라고요!

[FEAT] 내 프로필 조회 API 구현

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/exception/AuthExceptionType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/service/AuthService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/entity/Member.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/repository/MemberRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/oauth/service/NaverAuthService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/oauth/service/vo/NaverMemberVO.java

- fix/#41 -> dev
- closed #41
- Member 엔티티에 platformId를 추가했습니다 (소셜 플랫폼에서 회원을 구분하는 id)
- 이에 따라 빌더 패턴도 수정하였습니다
- Member 테이블에 platformType과 platformId의 조합이 중복될 수 없도록 unique 제약조건을 추가했습니다
- 추상 메서드(AuthService)와 구현 클래스인(NaverAuthService)에서 트랜잭션 어노테이션을 붙이는 것에 대해 고민이 많았는데 구현체의 비지니스 로직에 따라 트랜잭션이 유지되도록 구현 클래스 메서드 위에 명시적으로 옮겨보았는데 어떠신지도 궁금합니다

[FIX] 네이버 소셜 로그인 동시성 이슈 해결

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/error/GlobalExceptionHandler.java
nonsoolmateServer/src/main/resources/application-test.yml
nonsoolmateServer/src/test/java/com/nonsoolmate/nonsoolmateServer/domain/member/repository/MemberRepositoryTest.java

- test/#68 -> dev
- closed #68
- repository 단에서 회원가입 로직에 해당하는 함수에 대하여 2가지 테스트케이스를 작성하였습니다
- case1. service 단에서 트랜잭션 실행 시점 차이로 인해 이미 저장된 회원에 대하여 한번 더 테이블에 추가하려는 시도일 경우
- case2. 동시에 테이블에 추가하는 요청이 오는 경우
- 서비스 단 코드도 작성하고 싶었으나 webClient mocking 과정에서 체이닝을 맞추어주는 방식이 memberVO와 tokenVO를 가져오는 과정에서 차이가 있어 어렵더라고요.. 이런 의존성이 많으면 코드가 별로라는 뜻인데, 저희 스프린트 상 현재 이 부분을 집중해서 고치기에는 무리가 있다고 판단되어 repository 단에서의 코드만으로 검증을 했습니다
- 테스트코드 논메에서 짜니까 ..새롭네요 ^^~ 좋은 의견 많이많이 부탁드림

[TEST] 네이버 소셜 로그인 동시성 테스트 작성

---

nonsoolmateServer/build.gradle
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/common/random/CustomRandom.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/common/random/MockRandom.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/common/random/RealRandom.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/coupon/controller/CouponApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/coupon/controller/CouponController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/coupon/controller/dto/request/IssueCouponRequestDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/coupon/controller/dto/response/GetCouponResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/coupon/controller/dto/response/GetCouponsResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/coupon/exception/CouponException.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/coupon/exception/CouponExceptionType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/coupon/repository/CouponRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/coupon/service/CouponService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/couponMember/entity/CouponMember.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/couponMember/repository/CouponMemberCustomRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/couponMember/repository/CouponMemberCustomRepositoryImpl.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/couponMember/repository/CouponMemberRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/controller/dto/request/RegisterCouponRequestDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/jwt/service/JwtService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/jwt/service/JwtTokenProvider.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/querydsl/config/QuerydslConfig.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/filter/JwtAuthenticationFilter.java
nonsoolmateServer/src/main/resources/application-dev.yml
nonsoolmateServer/src/main/resources/application-local.yml
nonsoolmateServer/src/main/resources/application-prod.yml
nonsoolmateServer/src/main/resources/application-test.yml
nonsoolmateServer/src/test/java/com/nonsoolmate/nonsoolmateServer/domain/member/repository/MemberRepositoryTest.java

feat/#81
closed #81 
- API 1개당 PR 1개를 올릴려고 했는데.. 기능이 간단해서.. 한 번에 올렸습니다...!
<br></br>
- 구현된 API는 다음과 같습니다.
- 쿠폰 발행 API (FE에서 사용 X)
- 쿠폰 조회 API
- 쿠폰 등록 API
관련 yml 수정도 진행하겠습니다!
- `LocaldateTime.now()` 나 `Random` 과 같이 통제할 수 없는 객체들은 Testability 를 낮추기 때문에 고민했는데요!
- 그래서 인터페이스를 사용해서 DI 방식으로 적용해봤습니다! 실제 비즈니스 로직에서는 RealRandom, 테스트코드 돌아갈 때는 MockRandom이 돌아가도록 설정해뒀습니다.
- 쿠폰 목록 조회할때, 프로젝션으로 구현하면 깔끔할 것 같아서 구현해봤습니다!
- JPQL 사용하려다가 `type-safety`한 `querydsl`를 선호해서 그렇게 구현해봤습니다

feat: 쿠폰 관련 로직 구현

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/coupon/controller/dto/response/GetCouponResponseDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/couponMember/repository/CouponMemberCustomRepositoryImpl.java
nonsoolmateServer/src/main/resources/application-local.yml

- closed #90
- 쿠폰 사용 시 가격 검증을 위해 사용자가 어떤 쿠폰을 사용하는지 알아야하기 때문에 CouponMember 테이블에서 사용되는 id를 dto에 추가했습니다.
- 본인이 등록한 쿠폰 2개 (쿠폰 id는 1로 동일)
- dto에 전달되는 id는 couponMember에 저장되어 있는 열의 id
- 쿠폰 로직을 다시 살펴보니 조회, 등록 같은 경우 CouponMember 도메인에서 이루어지는 로직이라는 생각이 드는데 coupon 도메인에 대부분의 코드가 작성되어 있더라고요?! getCoupons, registerCoupons는 CouponMember를 조회하거나 등록한다는 의미가 강한 것 같은데 service를 분리하시는건 어떤지 궁금합니다~ PR 날려주셨을 때 확인했어야 하는 부분인데 뒤늦게 리뷰 남겨 죄송합니다!
- 그리고 getCoupons에서 사용자의 쿠폰을 조회한다는 느낌의 메서드명으로 변경하는건 어떤지.. ByMember를 붙인다던가 등등.. 궁금합니다 ㅎ

[FEAT] 사용자가 등록한 쿠폰 조회 API에서 사용하는 dto에 couponMemberId 추가

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/entity/ExamRecord.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/entity/enums/ExamResultStatus.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/repository/ExamRecordRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/service/ExamRecordService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectCollege/controller/SelectCollegeApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectCollege/controller/SelectCollegeController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectCollege/repository/SelectCollegeRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/selectCollege/service/SelectCollegeService.java
nonsoolmateServer/src/main/resources/application-local.yml

- feat/#92 -> dev
- 시험지 상태에 재첨삭 중, 재첨삭 완료를 추가했습니다
- 자세한 내용은 테크 스펙에 명시했습니다
- https://www.notion.so/nonsoolmatee/API-64d598c4aa374dd39f50afbe26c753f8?pvs=4 
- 클라를 위해 바로 머지하겠습니다! 리뷰 남겨주시면 따로 issue 파서 반영하겠습니다

[FEAT] 단과 대학별 시험지 리스트 조회에 재첨삭 플로우 구현

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/controller/ExamRecordApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/controller/ExamRecordController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/controller/dto/request/CreateExamRecordRequestDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/exception/ExamRecordExceptionType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/service/ExamRecordService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/entity/Member.java

- feat/#94
- closed #94
- 시험지 기록 요청 시 첨삭에 대한 시험 기록인지, 재첨삭에 대한 시험 기록인지에 따라 로직을 분리했습니다
- 자세한 내용은 테크 스펙 참고 부탁드립니다!
- https://www.notion.so/nonsoolmatee/API-76b766965a204d02a1e72504a99a5777?pvs=4
- 사용자가 응시한 적 없는 시험(첨삭)에 대해 시험 기록(첨삭)을 생성한 경우
- 사용자가 첨삭이 완료된 시험에 대해 재첨삭 시험 기록을 생성한 경우
- 사용자가 이미 응시한 시험(첨삭)에 대해 첨삭을 요청하는 경우
- 사용자가 이미 응시한 시험(재첨삭)에 대해 재첨삭을 요청하는 경우
- 사용자가 첨삭이 완료되지 않은 상태에서 재첨삭을 요청하는 경우
- 사용자가 첨삭을 받지 않고(첨삭에 대한 시험 기록을 생성하지 않고) 재첨삭을 요청하는 경우
- 일단 머지하겠습니다 나중에 리뷰 부탁드립니다!
- 테크 스펙에서 제가 고려하지 못한 예외 케이스가 있다면 조언 부탁드립니다

[FEAT] 재첨삭 플로우에 따른 시험지 기록 API 추가 구현

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/service/MemberService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/payment/controller/PaymentApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/payment/controller/PaymentController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/payment/controller/dto/response/CustomerInfoDTO.java

- feat/#102 -> dev
- closed #102
- 결제 위젯 호출에 필요한 사용자 정보를 조회할 수 있는 API를 개발했습니다
- memberService에서 불필요하게 회원을 한번 더 조회하는 로직에 대하여 이미 filter단에서 조회한 member로부터 getProfile에 필요한 정보를 반환하도록 리팩토링을 진행했습니다(이전에 마이페이지 추가로 오빠가 구현했던 기능인 것 같은데, 코드가 간단하여 해당 PR에서 같이 진행했습니다!)
- 지금 MemberService에서 Repository에 접근하는 로직이 전혀 없는데, transactional, service 어노테이션을 붙여두는게 나중을 위해서도 맞을까?라는 생각이 들었습니다!

[FEAT] 결제 위젯 호출을 위한 사용자 정보 조회 API 구현

---

nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/EditingResultController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/controller/EditingResultApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/controller/EditingResultController.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/controller/dto/response/EditingResultDTO.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/exception/ExamRecordExceptionType.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/repository/ExamRecordRepository.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/service/ExamRecordService.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/ExamApi.java
nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/ExamController.java
nonsoolmateServer/src/main/resources/application-local.yml

- feat/#104 -> dev
- closed #104
- 기존 ExamRecordController에서의 RequestMapping 경로를 university/exam-record에서 college/exam-record로 변경했습니다
- 기존의 첨삭 관련 API 경로(`/university/exam-record/{examId}`)를 다시 생각해보니 exam-record 뒤에 exam-record-id가 아닌 exam-id가 오는 것이 REST API 임을 고려했을 때 부자연스럽다는 생각이 들어 /college/exam/{exam-id}/exam-record ~ 형식으로 path를 지정해보았습니다
- 관련된 테크 스펙은 다음과 같습니다 -> https://www.notion.so/nonsoolmatee/_-API-d784c32cb7804b47b6db7b92857a975d?pvs=4 
- 첨삭 진행 중
- 첨삭 완료
- 첨삭을 제출하지 않은 시험지 조회 시
- 재첨삭 진행 중
- 재첨삭 완료
- 재첨삭을 제출하지 않은 시험지 조회 시

[FEAT] (재)첨삭 결과 조회 API 구현

---

nonsoolmate-api/src/main/java/com/nonsoolmate/examRecord/controller/ExamRecordApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/examRecord/controller/ExamRecordController.java
nonsoolmate-api/src/main/java/com/nonsoolmate/examRecord/service/ExamRecordService.java
nonsoolmate-common/src/main/java/com/nonsoolmate/exception/examRecord/ExamRecordExceptionType.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/examRecord/repository/ExamRecordRepository.java

- fix/#130 -> dev
- closed #130
- (재)첨삭이 완료되지 않은 경우에 대해 S3Service를 거치지 않고 file 경로를 바로 "" 빈 문자열로 반환하도록 수정했습니다
- 또한 MVP 개발 시에 사용되었던 첨삭_해제 PDF 조회 API와 첨삭 PDF 다운로드를 위해 만들었던 조회 API를 클라쪽에서 더 이상 사용하지 않는다고 하셔서 삭제했습니다

[FIX] (재)첨삭이 완료되지 않은 경우 file 경로가 빈 문자열로 내려가도록 수정

---

nonsoolmate-api/src/main/resources/discord-appender.xml
nonsoolmate-db-core/src/main/java/com/nonsoolmate/matching/entity/Matching.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/tag/entity/Tag.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/teacher/entity/Teacher.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/teacher/entity/TeacherUniversity.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/teacherMember/entity/TeacherMember.java

feat/#127 -> dev
closed #127 
- 첨삭 관련 테이블을 추가했습니다.
- Tag 라는 데이터가 선생님 뿐만 아니라 다른 도메인에서도 충분히 추가될 가능성이 높다고 생각했습니다.
- 그래서 관리하기 편하게 하나의 테이블에서 관리하려고 하는데요!
- 만약 시험관련해서 태그가 추가된다면, Tag 테이블에 exam_id 라는 컬럼을 추가해서 구현할 생각이었습니다!
- TeacherMember 은 선생님과 학생의 N:N 연결테이블입니다!

[FEAT] 첨삭 선생님 관련 테이블 추가

---

nonsoolmate-api/src/main/java/com/nonsoolmate/coupon/controller/CouponApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/examRecord/controller/EditingResultApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/examRecord/controller/ExamRecordApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MemberApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/CardApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/PaymentApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/selectCollege/controller/SelectCollegeApi.java

- feat/#138 -> dev
- closed #138
- @AuthMember 어노테이션으로 가져오는 memberId에 대해 swagger에서 Parameter(hidden=true)를 사용하여 테스트 시 memberId를 입력하지 않아도 되게 변경했습니다
- 방법 알려준 민규오빠 THX~

[FEAT] swagger에서 memberId 파라미터에 대해 hidden 속성 true로 지정

---

nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/CardApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/CardController.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/PaymentController.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/dto/request/CreateCardRequestDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/service/BillingService.java
nonsoolmate-api/src/main/resources/application-dev.yml
nonsoolmate-api/src/main/resources/application-local.yml
nonsoolmate-api/src/main/resources/application-prod.yml
nonsoolmate-api/src/main/resources/application-test.yml
nonsoolmate-common/src/main/java/com/nonsoolmate/exception/common/CommonErrorType.java
nonsoolmate-common/src/main/java/com/nonsoolmate/exception/payment/BillingExceptionType.java
nonsoolmate-external/src/main/java/com/nonsoolmate/toss/service/TossPaymentService.java
nonsoolmate-external/src/main/java/com/nonsoolmate/toss/service/dto/request/IssueBillingDTO.java
nonsoolmate-external/src/main/java/com/nonsoolmate/toss/service/dto/response/TossPaymentBillingDTO.java
nonsoolmate-external/src/main/java/com/nonsoolmate/toss/service/vo/TossPaymentBillingVO.java

- feat/#129
- closed #129
- 카드 등록 API를 구현했습니다
- 소영 언니에게 부탁해서 테스트까지 완료했습니다!
- 테스트는 내일 구현해서 별도로 PR push 해두겠습니다!!
- 카드 번호는 가렸습니다!

[FEAT] 카드 등록 API 구현

---

nonsoolmate-api/src/main/java/com/nonsoolmate/selectCollege/controller/SelectCollegeApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/selectCollege/controller/SelectCollegeController.java
nonsoolmate-api/src/main/java/com/nonsoolmate/selectCollege/controller/dto/request/SelectCollegeRequestDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/selectCollege/service/SelectCollegeService.java

- fix/#148 -> dev
- closed #148
- SelectCollege를 조회하고 그 안에서 단과 대학의 id를 가져와야하는데 SelectCollege의 pk를 가져오고 있어 null로 반환되는 문제를 확인하여 이를 수정했습니다!
- 이전 응답값 결과
- 코드 수정 후 응답값 결과

[FIX] 선택 단과 대학 시험지 리스트 조회 null로 넘어가는 문제 수정

---

nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/CardApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/CardController.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/dto/request/CreateOrUpdateCardRequestDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/service/BillingService.java
nonsoolmate-api/src/test/java/com/nonsoolmate/payment/service/BillingServiceTest.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/payment/entity/Billing.java

- feat/#150 -> dev
- closed #150
- 카드 변경 API를 구현했습니다
- 기존 등록 API와 외부 통신하는 함수는 동일하여 authKey를 클라이언트에게 요청드릴 수 없어 테스트 결과에 test code 성공여부 캡쳐본으로 대체했습니다!
- 카드를 변경하기 전 customerKey로 존재하는 billing을 조회하고 토스페이먼츠로부터 받은 값으로 카드정보 및 billingKey를 업데이트합니다
- 기획 요구사항에 따라 사용자 당 하나의 카드만 등록 가능하도록 customerKey를 unique를 추가했습니다

[FEAT] 카드 변경 API 구현

---

nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/CardApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/CardController.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/dto/request/CreateOrUpdateCardRequestDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/service/BillingService.java
nonsoolmate-api/src/test/java/com/nonsoolmate/payment/service/BillingServiceTest.java

- feat/#152 -> dev
- closed #152
#151 해당 PR에서 리뷰받은 내용을 반영하였습니다
- dto에서 customerKey를 제외하면서 customerKey가 조작되는 상황은 토큰이 조작되는 상황이라고 생각해 테스트의 책임이 BillingServiceTest가 아니라고 생각하여 제외했습니다!

[FEAT] 카드 등록, 변경 API에서 requestDTO에 customerKey 제외

---

nonsoolmate-api/src/main/java/com/nonsoolmate/member/service/MembershipService.java
nonsoolmate-api/src/main/java/com/nonsoolmate/order/service/OrderService.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/service/PaymentService.java
nonsoolmate-common/src/main/java/com/nonsoolmate/exception/member/MembershipExceptionType.java
nonsoolmate-common/src/main/java/com/nonsoolmate/exception/payment/PaymentExceptionType.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/entity/enums/MembershipType.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/product/entity/Product.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/product/entity/enums/ProductType.java

- feat/#175 -> dev
- closed #175 
- 저희 서비스의 종류가 첨삭, 재첨삭권이 포함되는 개념이라고 생각하여 기존 엔티티에 필드를 추가합니다
- review_ticket_count, re_review_ticket_count
- 상품 유형을 구분합니다(ProductType)
- 구독형 결제에 상품이 구독형 상품인지 검증하는 로직을 추가했습니다
- X
- MembershipType에서 description을 만들어 BASIC("베이직 플랜") 등으로 관리하여 상품 이름과 멤버십 타입을 매칭시켜 찾는 방식을 도입하는 것에 대해 궁금합니다!
- 현재 Membership 서비스에서는 static final 변수 선언을 통해 MembershipType enum을 찾고 있는데 좋은 방식 같지는 않아서요!

[FEAT] Product 엔티티 변경

---

nonsoolmate-api/src/main/java/com/nonsoolmate/payment/service/PaymentService.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/entity/Member.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/product/entity/Product.java

- feat/#170 -> dev
- closed #170
- 멤버십 구매 이후 첨삭권이 반영되는 로직을 구현했습니다
- 멤버십 반영 결과에서 3번째를 보시면 11개로 되어있는데, 해당 상품 구매시 첨삭권 1개, 재첨삭권 1개로 더미데이터가 세팅되어있었고, 회원에게 기존에 첨삭권 및 재첨삭권 각각 10개가 존재했습니다 이에 상품 구매 이후 11개로 변경된 모습입니다
- 결제 완료 화면
- 멤버십 반영 결과

[FEAT] 멤버십 구매 이후 첨삭권 개수 반영 로직 구현

---

nonsoolmate-api/src/main/java/com/nonsoolmate/discountProduct/service/DiscountProductService.java
nonsoolmate-api/src/main/java/com/nonsoolmate/global/config/SecurityConfig.java
nonsoolmate-api/src/main/java/com/nonsoolmate/product/controller/ProductApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/product/controller/ProductController.java
nonsoolmate-api/src/main/java/com/nonsoolmate/product/controller/dto/ProductResponseDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/product/service/ProductService.java
nonsoolmate-batch/src/main/java/com/nonsoolmate/payment/BillingPaymentService.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/discountProduct/entity/DiscountProduct.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/discountProduct/repository/DiscountProductRepository.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/product/entity/Product.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/product/repository/ProductRepository.java

- feat/#181 -> dev
- closed #181
- 상품 리스트 조회 API를 구현했습니다
- ProductResponseDTO에 상품 설명이 누락되어 필드를 추가했습니다
- Product와 DiscountProduct의 endDate가 빈 값일 수 있다고 생각해 처음에 not null 제약조건을 넣지 않았는데, 현재 판매하고 있는 + 적용되고 있는 할인 정보를 가져올 때 null이면 문제가 생길 것 같아 판매 기간이 정해지지 않더라도 임시로 값을 넣어둘 수 있도록 제약조건을 추가했습니다
- 위의 변경사항에 따라 할인 정보를 가져올 때 startDate와 endDate를 고려하는 로직은 따로 PR 날리겠습니다!
- 중복되는 로직을 리팩터링하는 과정을 함께 포함했습니다

[FEAT] 상품 리스트 조회 API 구현

---

nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MembershipApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MembershipController.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/GetUsedCouponResponseDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/PaymentInfoResponseDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/service/MembershipService.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/entity/Membership.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/order/repository/OrderRepository.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/product/entity/Product.java

- closed #164 
- 다음 달 결제 정보 조회 API 구현했습니다.

[FEAT] 다음 달 결제 정보 조회 API

---

nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/CardApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/controller/CardController.java
nonsoolmate-api/src/main/java/com/nonsoolmate/payment/service/BillingService.java
nonsoolmate-api/src/test/java/com/nonsoolmate/payment/service/BillingServiceTest.java

- feat/#194 -> dev
- closed #194 
- 사용자가 카드를 등록하지 않고 조회하는 경우에 대해 결제 페이지에서는 플로우가 예외는 아닌 것 같아 404 not found에서 No Content로 변경했습니다
- 카드가 없는 경우

[FEAT] 카드 정보 조회 시 사용자가 등록한 카드가 없는 경우에 대해 204(No Content) 응답값으로 변경

---

nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MembershipApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MembershipController.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/request/MembershipStatusRequestDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/MembershipStatusResponseDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/service/MembershipService.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/entity/Member.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/entity/Membership.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/entity/enums/MembershipType.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/repository/MembershipRepository.java
nonsoolmate-exception/src/main/java/com/nonsoolmate/exception/member/MembershipExceptionType.java

- feat/#173 -> dev
- closed #173 
- 멤버십 상태를 변경하는 API를 구현했습니다
- 해지로 변경
- 연장하기로 변경
- 멤버십이 없는 상태에서 상태 변경을 요청하는 경우

[FEAT] 멤버십 상태 변경 API 구현

---

nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MembershipApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MembershipController.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/service/MembershipService.java

- feat/#172 -> dev
- closed #172
- 멤버십이 존재하는 경우에는 OK, 없는 경우에는 NoContent로 응답합니다
- 멤버십이 존재하지 않는 경우
- 멤버십이 존재하는 경우

[FEAT] 멤버십 조회 API 구현

---

nonsoolmate-batch/src/main/java/com/nonsoolmate/scheduler/BillingScheduler.java
nonsoolmate-batch/src/main/java/com/nonsoolmate/scheduler/MembershipScheduler.java
nonsoolmate-batch/src/main/java/com/nonsoolmate/service/BillingPaymentService.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/member/repository/MembershipRepository.java

- feat/#174 -> dev
- closed #174 
- 멤버십을 삭제해야 할 회원들의 membershipId를 조회하여 한번에 삭제하는 기능을 구현했습니다
- 스케줄러 가동 전
- 스케줄러 가동 후
- 스케줄러 모듈은 현재 배포되지 않고 있는게 맞을까요??

[FEAT] 멤버십을 해지하고 유효기간이 지난 회원을 membership 테이블에서 삭제하는 스케줄러 구현

---

nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/MembershipApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/MembershipAndTicketResponseDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/MembershipStatusResponseDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/member/service/MembershipService.java
nonsoolmate-api/src/test/java/com/nonsoolmate/member/service/MembershipServiceTest.java

- fix/#206 -> dev
- closed #206 
- 모달창에서 성별에 대한 필드값을 추가했습니다
- 멤버십 조회에서 멤버십 시작날짜와 종료날짜를 구분하여 보내도록 수정했습니다
- 모달창
- 멤버십 조회

[FIX] 모달창, 멤버십 조회 응답값 수정

---

nonsoolmate-api/src/main/java/com/nonsoolmate/examRecord/controller/EditingResultApi.java
nonsoolmate-api/src/main/java/com/nonsoolmate/examRecord/controller/EditingResultController.java
nonsoolmate-api/src/main/java/com/nonsoolmate/examRecord/controller/dto/request/CreateExamRecordRequestDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/examRecord/controller/dto/request/UpdateExamRecordResultRequestDTO.java
nonsoolmate-api/src/main/java/com/nonsoolmate/examRecord/service/ExamRecordService.java
nonsoolmate-api/src/main/java/com/nonsoolmate/global/config/AsyncConfig.java
nonsoolmate-api/src/main/java/com/nonsoolmate/global/config/SecurityConfig.java
nonsoolmate-api/src/main/java/com/nonsoolmate/global/event/EmailEventListener.java
nonsoolmate-api/src/main/java/com/nonsoolmate/global/event/ExamRecordStatusUpdatedEvent.java
nonsoolmate-api/src/main/resources/application-dev.yml
nonsoolmate-api/src/main/resources/application-local.yml
nonsoolmate-api/src/main/resources/application-prod.yml
nonsoolmate-api/src/main/resources/application-test.yml
nonsoolmate-batch/src/main/resources/application.yml
nonsoolmate-db-core/src/main/java/com/nonsoolmate/examRecord/entity/ExamRecord.java
nonsoolmate-external/build.gradle
nonsoolmate-external/src/main/java/com/nonsoolmate/email/config/EmailConfig.java
nonsoolmate-external/src/main/java/com/nonsoolmate/email/service/EmailService.java
nonsoolmate-external/src/main/resources/templates/examRecordStatusTemplate.html

- feat/#108 -> dev
- closed #108
- 첨삭 결과를 기록하는 ADMIN용  API를 구현했습니다
- 이벤트 리스터를 통해 API 호출 시 첨삭을 요청한 학생에게 이메일이 발송되도록 로직을 구현했습니다
- 트랜잭션이 커밋되었을 때에만 이메일을 발송합니다 
- 구현 템플릿은 다음과 같습니다
- 디자이너의 답변에 따라 템플릿은 조금 수정될 수 있을 것 같습니다! 네이버와 gmail을 확인해봤을 때 기본 이미지가 다 다르게 보여지고있어 문의한 상태입니다!

[FEAT] 첨삭 상태 변경 시 이메일 발송 로직 구현

---

nonsoolmate-api/src/main/java/com/nonsoolmate/payment/service/PaymentService.java
nonsoolmate-batch/src/main/java/com/nonsoolmate/service/BillingPaymentService.java
nonsoolmate-db-core/src/main/java/com/nonsoolmate/order/entity/OrderDetail.java

- feat/#210 -> dev
- closed #210 
- 결제 API에서 처음에 생성되어 결제되는 Order의 isPayment 상태를 true로 업데이트하는 로직을 추가했습니다
- 스케줄러에서도 결제된 order에 대해서는 isPayment의 상태를 true로 변경하도록 반영했습니다
- OrderDetail 엔티티에 isPayment를 true로 변경하는 메서드를 만들었습니다
- Default 컬럼 값이 dev db에서 적용되지 않는 것 같아 alter문으로 dev,prod 모두 default 값을 지정해두었습니다
- OrderDetail에 추가한 markAsPaid라는 메서드명이 괜찮을지, 해당 메서드가 쿠폰처럼 사용여부를 등록했다가 다시 false로 돌리는 경우가 발생할 수 있어 파라미터로 boolean 값을 받는게 좋을지에 대해 이야기해보고 싶습니다!!

[FEAT] 결제가 완료된 order에 대해서 isPayment 필드값 업데이트 로직 반영
